apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-nodejs-app
spec:
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: image
        type: image
  stepTemplate:
  steps:
    - name: create-image-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - "--cache=true"
        - "--dockerfile=./source/ci-cd-pipeline/tekton-kubernetes/Dockerfile"
        - "--destination=$(outputs.resources.image.url)"
        - "--context=$(inputs.resources.source.path)/"
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/kaniko-secret.json
      volumeMounts:
      - name: kaniko-secret
        mountPath: /secret
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
        defaultMode: 0400
